# Generated by Django 4.2.4 on 2023-08-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_message',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('message', models.CharField(blank=True, max_length=600)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
